name: chairing
channels:
  - defaults
  - conda-forge
dependencies:
  - blas=1.0
  - bottleneck=1.3.5
  - bzip2=1.0.8
  - ca-certificates=2022.07.19
  - certifi=2022.6.15
  - freetype=2.11.0
  - giflib=5.2.1
  - intel-openmp=2021.4.0
  - jpeg=9e
  - lcms2=2.12
  - lerc=3.0
  - libcxx=12.0.0
  - libdeflate=1.8
  - libffi=3.3
  - libpng=1.6.37
  - libtiff=4.4.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - lz4-c=1.9.3
  - make=4.2.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - numexpr=2.8.3
  - numpy=1.23.1
  - numpy-base=1.23.1
  - openssl=1.1.1q
  - packaging=21.3
  - pandas=1.4.3
  - pillow=9.2.0
  - pip=22.1.2
  - pyparsing=3.0.9
  - python=3.10.4
  - python-dateutil=2.8.2
  - pytz=2022.1
  - readline=8.1.2
  - reportlab=3.5.67
  - setuptools=63.4.1
  - six=1.16.0
  - sqlite=3.39.2
  - tk=8.6.12
  - tzdata=2022a
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - black==22.8.0
    - click==8.1.3
    - mypy-extensions==0.4.3
    - pathspec==0.10.0
    - platformdirs==2.5.2
    - tomli==2.0.1
